### ISSUE TITLE
Steam cannot be opened because of a problem

### ISSUE THREAD

**Issue by SchlesserYannick** [JK3Y/asepsis#16]
For some reason, after installation, the Steam application does not open and throws some vague error. Any idea on how to fix it ?

<img width="752" alt="screenshot 2019-03-06 at 00 48 23" src="https://user-images.githubusercontent.com/26067446/53845481-972f6780-3fa9-11e9-946f-3479d3d1ab62.png">

**Comment by JK3Y** [comment]
I've updated the code in the repository, please retry with the new code to see if it fixes your problem.

**Comment by SchlesserYannick** [comment]
As woutgg mentioned in the referenced issue, it didn't fix the problem, unfortunately.
